name: Deploy Frontend to Azure Static Web Apps
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Extract Frontend Application
      run: |
        mkdir -p frontend-extracted
        unzip webapp-code/frontend.zip -d frontend-extracted
        ls -la frontend-extracted/
    
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "frontend-extracted"
        output_location: ""
        skip_app_build: true
